# 1. Regresión lineal con regularización

Función a optimizar:

$J(\theta) = (y-X\theta)^T(y-X\theta) + \delta^2\theta^T\theta$


Gradiente: 

$\nabla J(\theta) = -2X^Ty + 2\theta(X^TX + \delta^2)$

In [1]:
import numpy as np

In [52]:
def j(theta):
    return (y-theta.T@X.T)@(y-X@theta) + delta*delta*(theta.T@theta)

def nabla_j(theta):
    return (-2*X.T@y) + 2*X.T@X@theta + 2*delta*delta*theta

def get_alpha(alpha, xk, pk, f, nabla_f):
    c = 1e-4
    rho = 0.01
    a = alpha
    while (f(xk + alpha*pk) <= f(xk) + c*a*nabla_f(xk)@pk):
        a += rho
    return a

def gradient_descent(f, nabla_f, x0, init_alpha, num_iter=1e2):
    xk = x0
    alpha = init_alpha
    print(xk)
    for _ in range(int(num_iter)):
        pk = -1*nabla_f(xk)
        alpha = get_alpha(alpha, xk, pk, f, nabla_f)
        xk = xk + alpha*pk
        print(xk)
    return xk

In [53]:
X = np.array([
    [1,100,2],
    [1,50,42],
    [1,45,31],
    [1,60,35]
])
y = np.array([5,25,22,18])

delta = 0.1
alpha = 0.1
x0 = np.array([24,0,0])

gradient_descent(j, nabla_j, init_alpha=alpha, x0=x0, num_iter=10)

[24  0  0]
[  18.752 -460.     -53.6  ]
[  24656.912896 1728970.968     575535.2432  ]
[-1.00834399e+08 -6.93409633e+09 -2.45897822e+09]
[4.07716468e+11 2.79842773e+13 9.98094192e+12]
[-1.64669814e+15 -1.13003782e+17 -4.03257150e+16]
[6.65003257e+18 4.56347417e+20 1.62856941e+20]
[-2.68552543e+22 -1.84289430e+24 -6.57677695e+23]
[1.08451201e+26 7.44227070e+27 2.65594047e+27]
[-4.37965022e+29 -3.00545699e+31 -1.07256448e+31]
[1.76866053e+33 1.21371180e+35 4.33140174e+34]


array([1.76866053e+33, 1.21371180e+35, 4.33140174e+34])