In [1]:
import numpy as np

In [14]:
A = np.array([
    [3, 2, 2],
    [2, 3, -2]
])
print(f'A=\n{A}\n-----------------')
U, S, Vt = np.linalg.svd(A)
print(f'A= U S V^T\nU=\n{U}\nS=\n{S}\nV^T=\n{Vt}')

A=
[[ 3  2  2]
 [ 2  3 -2]]
-----------------
A= U S V^T
U=
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
S=
[5. 3.]
V^T=
[[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


In [10]:
4/np.sqrt(18)

0.9428090415820635