# Ejercicio 1

In [6]:
import numpy as np
from math import sqrt

def equal_matrixes(A, B):
    if len(A) == len(B) and len(A[0]) == len(B[0]):
        equal = True
        for i in range(len(A)):
            for j in range(len(A[i])):
                if A[i][j] == B[i][j]: 
                    pass
                else:
                    equal = False
                    break
        return equal
    else:
        return False

def zeros_in_diag(A):
    no_zeros = True
    for i in range(0, len(A)):
        for j in range(0, len(A[0])):
            if i == j: 
                if A[i][j] == 0: 
                    no_zeros = False
                    break
    return no_zeros

def validate_matrix(A):
    eq_transpose = True if equal_matrixes(A, A.transpose()) else False
    diag_zero = True if zeros_in_diag(A) else False
    msg_diag = 'Matrix cannot have zeros on the main diagonal'
    msg_transpose = 'Matrix must be equal to its transpose'
    if diag_zero == False: return (False, msg_diag)
    if eq_transpose == False: return (False, msg_transpose)
    return (True, '')

def symmetric_matrix(n):
    numbers = np.random.randint(low = -100, high = 100, size = 100)
    A = np.random.choice(numbers, size=(n, n))
    return np.tril(A) + np.tril(A, -1).T

def random_squared_matrix_cholesky(n):
    A = np.random.rand(n, n)
    B = np.dot(A,A.transpose())
    return B

def cholesky(A):
    L = np.zeros((len(A), len(A)))
    L[:,0] = A[:,0] / sqrt(A[0][0])
    for i in range(0, len(L)):
        for j in range(0, len(L[0])):
            if j < i or j == i:
                if j == i:
                    s = 0
                    for k in range(0, i):
                        s += L[j][k] ** 2
                    L[i][j] = sqrt(A[i][j] - s)
                else:
                    s = 0
                    for k in range(0, j):
                            s += L[i][k] * L[j][k]
                    L[i][j] = (1 / L[j][j]) * (A[i][j] - s)
    return L

In [8]:
A = np.array([[1,-1,1], [-1,5,-5], [1,-5,6]])
(case, msg) = validate_matrix(A)
if case :
    L = cholesky(A)
    LT = L.T
    print("A: \n", A)
    print("L: \n", L)
    print("LT: \n", LT)
    print("L*LT: \n", L.dot(LT))
else:
    print(msg)

A: 
 [[ 1 -1  1]
 [-1  5 -5]
 [ 1 -5  6]]
L: 
 [[ 1.  0.  0.]
 [-1.  2.  0.]
 [ 1. -2.  1.]]
LT: 
 [[ 1. -1.  1.]
 [ 0.  2. -2.]
 [ 0.  0.  1.]]
L*LT: 
 [[ 1. -1.  1.]
 [-1.  5. -5.]
 [ 1. -5.  6.]]


# Ejercicio 2


## c)

In [7]:
def X(y,z):
    return (7-2*y-z)/10
def Y(x,z):
    return (-8-x-z)/5
def Z(x,y):
    return (6-2*x-3*y)/10

def jacobi(n_iter, seed):
    for i in range(-1, n_iter):
        x,y,z = seed
        n_x, n_y, n_z = X(y,z), Y(x, z), Z(x, y)
        Di = max(abs(n_x - x), abs(n_y - y), abs(n_z - z))
        seed = (n_x, n_y, n_z)
        print(f'Iteración #{i+1}: \tx: {x} \ty: {y} \tz: {z} \t\t D{i+1}: {Di}')
    final = (round(n_x), round(n_y), round(n_z))
    return final

In [10]:
f = jacobi(7, (0.7,-1.6,0.6))
print(f)

Iteración #0: 	x: 0.7 	y: -1.6 	z: 0.6 		 D0: 0.3400000000000001
Iteración #1: 	x: 0.96 	y: -1.8599999999999999 	z: 0.9400000000000001 		 D1: 0.1200000000000001
Iteración #2: 	x: 0.978 	y: -1.98 	z: 0.966 		 D2: 0.032399999999999984
Iteración #3: 	x: 0.9994000000000002 	y: -1.9888 	z: 0.9984 		 D3: 0.010760000000000103
Iteración #4: 	x: 0.9979199999999999 	y: -1.99956 	z: 0.9967600000000001 		 D4: 0.0035240000000000826
Iteración #5: 	x: 1.000236 	y: -1.998936 	z: 1.0002840000000002 		 D5: 0.0011679999999998358
Iteración #6: 	x: 0.9997588000000001 	y: -2.000104 	z: 0.9996335999999999 		 D6: 0.00044584000000003066
Iteración #7: 	x: 1.0000574400000002 	y: -1.99987848 	z: 1.00007944 		 D7: 0.0001488960000002315
(1, -2, 1)


## d)

In [12]:
jacobi(20, (-5,3,5))

Iteración #0: 	x: -5 	y: 3 	z: 5 		 D0: 4.6
Iteración #1: 	x: -0.4 	y: -1.6 	z: 0.7 		 D1: 1.35
Iteración #2: 	x: 0.95 	y: -1.6599999999999997 	z: 1.1600000000000001 		 D2: 0.3620000000000001
Iteración #3: 	x: 0.916 	y: -2.022 	z: 0.9079999999999998 		 D3: 0.11540000000000006
Iteración #4: 	x: 1.0136 	y: -1.9647999999999999 	z: 1.0233999999999999 		 D4: 0.04260000000000019
Iteración #5: 	x: 0.9906200000000001 	y: -2.0074 	z: 0.9867199999999998 		 D5: 0.01737600000000028
Iteración #6: 	x: 1.0028080000000001 	y: -1.995468 	z: 1.004096 		 D6: 0.006017200000000056
Iteración #7: 	x: 0.9986839999999999 	y: -2.0013808 	z: 0.9980788 		 D7: 0.0025986399999999854
Iteración #8: 	x: 1.00046828 	y: -1.9993525600000002 	z: 1.00067744 		 D8: 0.000965327999999932
Iteración #9: 	x: 0.999802768 	y: -2.000229144 	z: 0.9997121120000001 		 D9: 0.0003960775999998223
Iteración #10: 	x: 1.0000746176 	y: -1.999902976 	z: 1.0001081896 		 D10: 0.00015222031999995167
Iteración #11: 	x: 0.9999697762399998 	y: -2.0

(1, -2, 1)

In [13]:
jacobi(20, (100,-500,-350))

Iteración #0: 	x: 100 	y: -500 	z: -350 		 D0: 548.4
Iteración #1: 	x: 135.7 	y: 48.4 	z: 130.6 		 D1: 171.66
Iteración #2: 	x: -22.04 	y: -54.85999999999999 	z: -41.059999999999995 		 D2: 65.88
Iteración #3: 	x: 15.777999999999997 	y: 11.02 	z: 21.465999999999998 		 D3: 27.327599999999997
Iteración #4: 	x: -3.6506 	y: -9.0488 	z: -5.8616 		 D4: 9.90636
Iteración #5: 	x: 3.09592 	y: 0.30244 	z: 4.04476 		 D5: 4.154676
Iteración #6: 	x: 0.23503600000000002 	y: -3.028136 	z: -0.10991599999999999 		 D6: 1.5713495999999998
Iteración #7: 	x: 1.3166188 	y: -1.6250240000000002 	z: 1.4614335999999999 		 D7: 0.6372501599999997
Iteración #8: 	x: 0.87886144 	y: -2.15561048 	z: 0.8241834400000002 		 D8: 0.2467274159999998
Iteración #9: 	x: 1.048703752 	y: -1.940608976 	z: 1.070910856 		 D9: 0.09846891359999999
Iteración #10: 	x: 0.9810307096 	y: -2.0239229215999996 	z: 0.9724419424 		 D10: 0.038528792159999825
Iteración #11: 	x: 1.00754039008 	y: -1.9906945304 	z: 1.0109707345599999 		 D11: 0.0152

(1, -2, 1)

## f)

In [17]:
import numpy as np 

def f_x(y, z):
    return (7-2*y-z)/10
def f_y(x, z):
    return (-8-x-z)/5
def f_z(x, y):
    return (6-2*x-3*y)/10

def gaus_siedel(seed, n_iter, verbose=False):
    for i in range(-1, n_iter):
        x,y,z = seed
        n_x = f_x(y,z)
        n_y = f_y(n_x, z)
        n_z = f_z(n_x, n_y)
        seed = (n_x, n_y, n_z)
        Di = max(abs(n_x - x), abs(n_y - y), abs(n_z - z))
        if verbose:
            print(f'Iteración #{i+1}: \tx: {x} \ty: {y} \tz: {z} \t\t {Di}')
    final = (round(n_x, 4), round(n_y, 4), round(n_z, 4))
    return final

In [19]:
gaus_siedel((0.7, -1.6, 0.6), 10, verbose=True)

Iteración #0: 	x: 0.7 	y: -1.6 	z: 0.6 		 0.38160000000000005
Iteración #1: 	x: 0.96 	y: -1.9120000000000001 	z: 0.9816 		 0.0811679999999999
Iteración #2: 	x: 0.98424 	y: -1.993168 	z: 1.0011024000000002 		 0.014283359999999856
Iteración #3: 	x: 0.9985233599999999 	y: -1.999925152 	z: 1.0002728736 		 0.0014343830400002089
Iteración #4: 	x: 0.9999577430400001 	y: -2.000046123328 	z: 1.0000222883904002 		 4.92527865597614e-05
Iteración #5: 	x: 1.0000069958265598 	y: -2.000005856843392 	z: 1.0000003578877057 		 5.860246651945289e-06
Iteración #6: 	x: 1.0000011355799079 	y: -2.0000002986935224 	z: 0.9999998624920752 		 1.0620904109526208e-06
Iteración #7: 	x: 1.000000073489497 	y: -1.9999999871963143 	z: 0.9999999814609948 		 7.419633352157007e-08
Iteración #8: 	x: 0.9999999992931634 	y: -1.9999999961508315 	z: 0.9999999989866166 		 3.5127929454148443e-09
Iteración #9: 	x: 0.9999999993315047 	y: -1.9999999996636244 	z: 1.0000000000327864 		 5.979415851342651e-10
Iteración #10: 	x: 0.99999

(1.0, -2.0, 1.0)

In [20]:
gaus_siedel((100, -500, -350), 20, verbose=True)

Iteración #0: 	x: 100 	y: -500 	z: -350 		 541.26
Iteración #1: 	x: 135.7 	y: 41.260000000000005 	z: -38.918 		 139.3602
Iteración #2: 	x: -3.660200000000001 	y: 6.915640000000001 	z: -0.742652 		 8.24533704
Iteración #3: 	x: -0.6088628000000001 	y: -1.32969704 	z: 1.1206816720000001 		 1.4627340408
Iteración #4: 	x: 0.8538712408 	y: -1.99491058256 	z: 1.0276989266079999 		 0.14234098305120002
Iteración #5: 	x: 0.9962122238512 	y: -2.0047822300918403 	z: 1.002192224257312 		 0.00452499974143683
Iteración #6: 	x: 1.0007372235926368 	y: -2.0005858895699897 	z: 1.0000283221524695 		 0.0006228778938859314
Iteración #7: 	x: 1.000114345698751 	y: -2.0000285335702443 	z: 0.9999856909313231 		 0.00010720807783437536
Iteración #8: 	x: 1.0000071376209165 	y: -1.9999985657104478 	z: 0.999998142188951 		 7.238697722122822e-06
Iteración #9: 	x: 0.9999998989231944 	y: -1.9999996082224292 	z: 0.9999999026820898 		 3.585892440760574e-07
Iteración #10: 	x: 0.999999931376277 	y: -1.9999999668116732 	z: 

(1.0, -2.0, 1.0)