# Descomposición LU
### Métodos Matemáticos Computacionales para Ciencia de Datos
*Martínez Ostoa Néstor Iván*

Descomposición LU por los métodos de *Doolittle-Crout* y *Cholesky*

In [2]:
import numpy as np
from math import sqrt
from scipy import random, linalg

In [3]:
def initLU(n):
    L = np.eye(n)
    U = np.zeros((n, n))
    return (L, U)

def doolittle(A, n):
    (L, U) = initLU(n)
    U[0] = A[0] / L[0][0]
    L[:, 0] = A[:, 0] / U[0][0]
    for i in range(1, len(A)):
        for j in range(0, len(A[0])):
            if j >= i: # obtain U matrix
                s = 0
                for k in range(0, i):
                    s += L[i][k] * U[k][j]
                U[i][j] = A[i][j] - s
            else: # obtain L matri
                if i > 1 and j > 0:
                    s = 0
                    for k in range(0, j):
                        s += L[i][k] * U[k][j]
                    L[i][j] = (1 / U[j][j]) * (A[i][j] - s)
    return (L, U)

In [4]:
def random_squared_matrix(n):
    return np.random.rand(n, n)

In [8]:
#A =  np.array([[6, 2, 1, -1], [2, 4, 1, 0], [1, 1, 4, -1], [-1, 0, -1, 3]])
#n = 4
#A = random_squared_matrix(n)
A = np.array([[-4, -3, 1], [8, 11, -1], [4, 18, 5]]) #LU
A = np.array([[6, 15, 55], [15, 55, 225], [55, 225, 979]]) #Cholesky
A = np.array([[-1, -1, 1], [1, 3, 3], [-1, -1, 5], [1, 3, 7]]) #QR


A = np.array([
  [2,5],
  [-4,3]
])

(L, U) = doolittle(A, 2)
print("A matrix: \n", A)
print("L matrix: \n", L)
print("U matrix: \n", U)
print("LU matrix: \n", L.dot(U))

A matrix: 
 [[ 2  5]
 [-4  3]]
L matrix: 
 [[ 1.  0.]
 [-2.  1.]]
U matrix: 
 [[ 2.  5.]
 [ 0. 13.]]
LU matrix: 
 [[ 2.  5.]
 [-4.  3.]]


## Choleski
Supongamos la misma matriz $A$ de dimensiones $nxn$, para este método la podemos descomponer de la siguiente manera: $A = LL^T$

$l_{11} = \sqrt a_{11}$

$l_{j1} = \frac{a_{j1}}{l_{11}}$

$l_{ii} = \sqrt{a_{ii} - \sum^{i-1}_{k = 1}l_{ik}^2}$

$l_{ji} = \frac{1}{l_{ii}}(a_{ji} - \sum^{i-1}_{k=1}l_{jk}l_{ik})$


In [7]:
def equal_matrixes(A, B):
    if len(A) == len(B) and len(A[0]) == len(B[0]):
        equal = True
        for i in range(len(A)):
            for j in range(len(A[i])):
                if A[i][j] == B[i][j]: 
                    pass
                else:
                    equal = False
                    break
        return equal
    else:
        return False

def zeros_in_diag(A):
    no_zeros = True
    for i in range(0, len(A)):
        for j in range(0, len(A[0])):
            if i == j: 
                if A[i][j] == 0: 
                    no_zeros = False
                    break
    return no_zeros

def validate_matrix(A):
    eq_transpose = True if equal_matrixes(A, A.transpose()) else False
    diag_zero = True if zeros_in_diag(A) else False
    msg_diag = 'Matrix cannot have zeros on the main diagonal'
    msg_transpose = 'Matrix must be equal to its transpose'
    if diag_zero == False: return (False, msg_diag)
    if eq_transpose == False: return (False, msg_transpose)
    return (True, '')

def symmetric_matrix(n):
    numbers = np.random.randint(low = -100, high = 100, size = 100)
    A = np.random.choice(numbers, size=(n, n))
    return np.tril(A) + np.tril(A, -1).T

def random_squared_matrix_cholesky(n):
    A = np.random.rand(n, n)
    B = np.dot(A,A.transpose())
    return B

In [9]:
def cholesky(A):
    L = np.zeros((len(A), len(A)))
    L[:,0] = A[:,0] / sqrt(A[0][0])
    for i in range(0, len(L)):
        for j in range(0, len(L[0])):
            if j < i or j == i:
                if j == i:
                    s = 0
                    for k in range(0, i):
                        s += L[j][k] ** 2
                    L[i][j] = sqrt(A[i][j] - s)
                else:
                    s = 0
                    for k in range(0, j):
                            s += L[i][k] * L[j][k]
                    L[i][j] = (1 / L[j][j]) * (A[i][j] - s)
    return L

In [21]:
#A = np.array([[25, 15, -5, -10], [15, 10, 1, -7], [-5, 1, 21, 4], [-10, -7, 4, 18]])
n = 3
#A = random_squared_matrix_cholesky(n)
#A = np.array([[-4, -3, 1], [8, 11, -1], [4, 18, 5]]) #LU
A = np.array([[6, 15, 55], [15, 55, 225], [55, 225, 979]]) #Cholesky
#A = np.array([[-1, -1, 1], [1, 3, 3], [-1, -1, 5], [1, 3, 7]]) #QR

(case, msg) = validate_matrix(A)
if case :
    L = cholesky(A)
    LT = L.T
    print("A: \n", A)
    print("L: \n", L)
    print("LT: \n", LT)
    print("L*LT: \n", L.dot(LT))
else:
    print(msg)

A: 
 [[  6  15  55]
 [ 15  55 225]
 [ 55 225 979]]
L: 
 [[ 2.44948974  0.          0.        ]
 [ 6.12372436  4.18330013  0.        ]
 [22.45365598 20.91650066  6.11010093]]
LT: 
 [[ 2.44948974  6.12372436 22.45365598]
 [ 0.          4.18330013 20.91650066]
 [ 0.          0.          6.11010093]]
L*LT: 
 [[  6.  15.  55.]
 [ 15.  55. 225.]
 [ 55. 225. 979.]]
