# Descomposición LU
### Métodos Matemáticos Computacionales para Ciencia de Datos
*Martínez Ostoa Néstor Iván*

Descomposición LU por los métodos de *Doolittle-Crout* y *Cholesky*

In [177]:
import numpy as np
from math import sqrt
from scipy import random, linalg

In [51]:
def initLU(n):
    L = np.eye(n)
    U = np.zeros((n, n))
    return (L, U)

def doolittle(A, n):
    (L, U) = initLU(n)
    U[0] = A[0] / L[0][0]
    L[:, 0] = A[:, 0] / U[0][0]
    for i in range(1, len(A)):
        for j in range(0, len(A[0])):
            if j >= i: # obtain U matrix
                s = 0
                for k in range(0, i):
                    s += L[i][k] * U[k][j]
                U[i][j] = A[i][j] - s
            else: # obtain L matri
                if i > 1 and j > 0:
                    s = 0
                    for k in range(0, j):
                        s += L[i][k] * U[k][j]
                    L[i][j] = (1 / U[j][j]) * (A[i][j] - s)
    return (L, U)

In [53]:
def random_squared_matrix(n):
    return np.random.rand(n, n)

In [55]:
#A =  np.array([[6, 2, 1, -1], [2, 4, 1, 0], [1, 1, 4, -1], [-1, 0, -1, 3]])
n = 4
A = random_squared_matrix(n)
(L, U) = doolittle(A, n)
print("A matrix: \n", A)
print("L matrix: \n", L)
print("U matrix: \n", U)
print("LU matrix: \n", L.dot(U))

A matrix: 
 [[0.52616034 0.28769252 0.51883323 0.10216392]
 [0.60081993 0.10991621 0.00414064 0.22329023]
 [0.32638708 0.8281348  0.93333048 0.5815038 ]
 [0.5932058  0.2084529  0.99598565 0.65329757]]
L matrix: 
 [[ 1.          0.          0.          0.        ]
 [ 1.14189512  1.          0.          0.        ]
 [ 0.62031866 -2.97199575  1.          0.        ]
 [ 1.12742401  0.5301892  -0.63586129  1.        ]]
U matrix: 
 [[ 0.52616034  0.28769252  0.51883323  0.10216392]
 [ 0.         -0.21859848 -0.58831249  0.10662975]
 [ 0.          0.         -1.13697367  0.83503277]
 [ 0.          0.          0.          1.0125466 ]]
LU matrix: 
 [[0.52616034 0.28769252 0.51883323 0.10216392]
 [0.60081993 0.10991621 0.00414064 0.22329023]
 [0.32638708 0.8281348  0.93333048 0.5815038 ]
 [0.5932058  0.2084529  0.99598565 0.65329757]]


## Choleski
Supongamos la misma matriz $A$ de dimensiones $nxn$, para este método la podemos descomponer de la siguiente manera: $A = LL^T$

$l_{11} = \sqrt a_{11}$

$l_{j1} = \frac{a_{j1}}{l_{11}}$

$l_{ii} = \sqrt{a_{ii} - \sum^{i-1}_{k = 1}l_{ik}^2}$

$l_{ji} = \frac{1}{l_{ii}}(a_{ji} - \sum^{i-1}_{k=1}l_{jk}l_{ik})$


In [178]:
def equal_matrixes(A, B):
    if len(A) == len(B) and len(A[0]) == len(B[0]):
        equal = True
        for i in range(len(A)):
            for j in range(len(A[i])):
                if A[i][j] == B[i][j]: 
                    pass
                else:
                    equal = False
                    break
        return equal
    else:
        return False

def zeros_in_diag(A):
    no_zeros = True
    for i in range(0, len(A)):
        for j in range(0, len(A[0])):
            if i == j: 
                if A[i][j] == 0: 
                    no_zeros = False
                    break
    return no_zeros

def validate_matrix(A):
    eq_transpose = True if equal_matrixes(A, A.transpose()) else False
    diag_zero = True if zeros_in_diag(A) else False
    msg_diag = 'Matrix cannot have zeros on the main diagonal'
    msg_transpose = 'Matrix must be equal to its transpose'
    if diag_zero == False: return (False, msg_diag)
    if eq_transpose == False: return (False, msg_transpose)
    return (True, '')

def symmetric_matrix(n):
    numbers = np.random.randint(low = -100, high = 100, size = 100)
    A = np.random.choice(numbers, size=(n, n))
    return np.tril(A) + np.tril(A, -1).T

def random_squared_matrix_cholesky(n):
    A = np.random.rand(n, n)
    B = np.dot(A,A.transpose())
    return B

In [183]:
#A = np.array([[25, 15, -5, -10], [15, 10, 1, -7], [-5, 1, 21, 4], [-10, -7, 4, 18]])
n = 10
A = random_squared_matrix_cholesky(n)
(case, msg) = validate_matrix(A)
if case :
    L = cholesky(A)
    LT = L.T
    print("A: \n", A)
    print("L: \n", L)
    print("LT: \n", LT)
    print("L*LT: \n", L.dot(LT))
else:
    print(msg)

A: 
 [[2.96806241 2.41700191 2.58313704 2.06430036 2.67839275 2.17346423
  2.56001202 2.54172617 1.60855515 2.3324565 ]
 [2.41700191 3.43171453 2.97363    1.70225364 2.0756622  2.08745955
  2.51857198 2.77677332 1.65303873 2.21920618]
 [2.58313704 2.97363    5.08373263 2.06335305 3.72778734 3.42321865
  3.84972187 3.3899894  2.6232076  2.85874757]
 [2.06430036 1.70225364 2.06335305 1.9160063  2.12691914 1.91244321
  1.96168306 1.97602232 1.13059712 2.2500124 ]
 [2.67839275 2.0756622  3.72778734 2.12691914 3.77125306 2.63133661
  3.12737861 3.07740286 2.09410624 2.99143114]
 [2.17346423 2.08745955 3.42321865 1.91244321 2.63133661 3.01768094
  2.75682163 2.57947366 1.71678436 2.41519464]
 [2.56001202 2.51857198 3.84972187 1.96168306 3.12737861 2.75682163
  3.89256098 2.9114376  2.34674107 2.43181536]
 [2.54172617 2.77677332 3.3899894  1.97602232 3.07740286 2.57947366
  2.9114376  3.31514728 1.72222338 2.90779324]
 [1.60855515 1.65303873 2.6232076  1.13059712 2.09410624 1.71678436
  2.346

In [129]:
def cholesky(A):
    L = np.zeros((len(A), len(A)))
    L[:,0] = A[:,0] / sqrt(A[0][0])
    for i in range(0, len(L)):
        for j in range(0, len(L[0])):
            if j < i or j == i:
                if j == i:
                    s = 0
                    for k in range(0, i):
                        s += L[j][k] ** 2
                    L[i][j] = sqrt(A[i][j] - s)
                else:
                    s = 0
                    for k in range(0, j):
                            s += L[i][k] * L[j][k]
                    L[i][j] = (1 / L[j][j]) * (A[i][j] - s)
    return L