# Método de Diferencias Finitas
Martínez Ostoa Néstor

Este método se basa en el ejemplo de las ecuaciones diferenciales parciales (PDEs) elípticas (capítulo 9 del libro *Numerical Methods for Engineers and Scientists* de Joe Hoffman). Concretamente en el siguiente ejemplo: 

## Ejemplo: Sistemas térmicos

Tenemos dos sistemas térmicos para los cuales queremos conocer su temperatura $T(x,y)$ dado las coordenadas $(x,y)$. La distribución de la temperatura sobre estos sistemas térmicos está gobernada por la ecuación de dos dimensiones de Laplace: $$T_{xx} + T_{yy} = 0$$ más condiciones de frontera especificadas por los bordes del sistema. Para este caso en particular sí se conoce la solución analítica, es decir, la ecuación que dadas dos coordenadas $x,y$, se puede obtener la temperatura del sistema. Sin embargo, el **método de Diferencias Finitas** se aplica cuando no conocemos esta ecuación. Dicha ecuación es la siguiente: $$T(x,y) = 100 \frac{\sinh(\pi y / w)\sin(\pi x/w)}{\sinh (\pi h / w)}$$ En la siguiente celda tenemos los valores al sustituir valores de $x,y$. El ejemplo indica que tenemos una placa con $w=10\; \text{cm}$ de ancho y $h=15\; \text{cm}$ de alto.



In [24]:
import numpy as np 
def analytical_solution(x,y):
    w = 10
    h = 15
    return 100 * ((np.sinh((np.pi*y)/w)*np.sin((np.pi*x)/w))/(np.sinh((np.pi*h)/w)))

for x in [0,1.25,2.5,3.75,5]:
    for y in np.linspace(15,0,13):
        print(f'x={x}\ty={y}\t\tT(x,y)={analytical_solution(x,y)}')
    print()


x=0	y=15.0		T(x,y)=0.0
x=0	y=13.75		T(x,y)=0.0
x=0	y=12.5		T(x,y)=0.0
x=0	y=11.25		T(x,y)=0.0
x=0	y=10.0		T(x,y)=0.0
x=0	y=8.75		T(x,y)=0.0
x=0	y=7.5		T(x,y)=0.0
x=0	y=6.25		T(x,y)=0.0
x=0	y=5.0		T(x,y)=0.0
x=0	y=3.75		T(x,y)=0.0
x=0	y=2.5		T(x,y)=0.0
x=0	y=1.25		T(x,y)=0.0
x=0	y=0.0		T(x,y)=0.0

x=1.25	y=15.0		T(x,y)=38.268343236508976
x=1.25	y=13.75		T(x,y)=25.837517849015125
x=1.25	y=12.5		T(x,y)=17.442631011620794
x=1.25	y=11.25		T(x,y)=11.772362975704958
x=1.25	y=10.0		T(x,y)=7.940991920414657
x=1.25	y=8.75		T(x,y)=5.350040150170044
x=1.25	y=7.5		T(x,y)=3.5947891392951923
x=1.25	y=6.25		T(x,y)=2.4010606458518557
x=1.25	y=5.0		T(x,y)=1.5823888152949586
x=1.25	y=3.75		T(x,y)=1.0108933605112747
x=1.25	y=2.5		T(x,y)=0.5973040756456376
x=1.25	y=1.25		T(x,y)=0.27701642134362275
x=1.25	y=0.0		T(x,y)=0.0

x=2.5	y=15.0		T(x,y)=70.71067811865476
x=2.5	y=13.75		T(x,y)=47.74150782320024
x=2.5	y=12.5		T(x,y)=32.22977956956618
x=2.5	y=11.25		T(x,y)=21.752490405094953
x=2.5	y=10.0		T(x,y)=14.673

## Método de diferencias finitias
Es un método numérico utilizado para resolver ecuaciones diferenciales parciales (PDEs) al **discretizar** el dominio continuo en una malla de pasos discreta. Concretamente, se aproximan las PDEs por medio de aproximaciones en diferencia finitas (FDAs), sustityuendo las FDAs en PDEs y resolviendo la ecuaciones en diferencias finita (FDEs) para la variable dependiente.

### Malla diferencias finitas
Esta malla abarca todo el dominio $D(x,y)$ del problema físico a resolver. La intersección de esta malla son los puntos en los cuales se obtiene la solución en diferencias finitas para la ecuacione diferencial parcial. 

Estas mallas tienen un espaciamiento en $x$ y en $y$, $\Delta x$, $\Delta y$ respectivamente pero **no** necesariamente se cumple que $\Delta x$ sea igual a $ \Delta y$. La función $f(x,y)$ en el punto de la malla $(i,j)$ se denota por $$f(x_i, y_i) = f_{ij}$$ y de manera análoga, las derivadas están denotadas por $\frac{\partial f(x_i, y_i)}{\partial x} = \frac{\partial f}{\partial x}\big |_{ij} = f_x|_{ij}$ y $\frac{\partial² f(x_i, y_i)}{\partial x^2} = \frac{\partial^2 f}{\partial x^2}\big |_{ij} = f_{xx}|_{ij}$

### Aproximaciones de Diferencias Finitas (FDAs)
Ahora, debemos desarrollar aproximaciones de diferencias finitas de las derivadas parciales de las ecuaciones diferenciales parciales. Para logar esto, empleamos la serie de Taylor para la variable dependiente. Antes, debemos dejar en claro la diferencia entre la solución exacta y la solución aproximada: $$\widehat{f}(x,y): \text{solución exacta}$$ $$f(x,y): \text{solución aproximada}$$

Concretamente, la aproximación, por medio del método de malla de diferencias finitas, de las derivadas parciales exactas en el punto de la malla $(i,j)$ se obtiene en términos de los valores de $\widehat{f}$ en el punto $(i,j)$ y puntos adyacentes a él dentro de la malla. 

### Solución de la ecuación de Laplace por medio de diferencias finitas

Para obtener esta solución emplearemos la serie de Taylor. Recordemos que la serie de Taylor de una función $f$ es la siguiente: $$f(x) = f(a) + f'(a)(x-a) + \frac{f''(x)}{2!}(x-a)^2 + \cdots + \frac{f^n(a)}{n!}(x-a)^n$$ y la ecuación de Laplace es la siguiente: $$\widehat{f}_{xx} + \widehat{f}_{yy} = 0$$

### Desarrollo de serie de Taylor para las segundas derivadas
$$ f(x_0 + \Delta x) = f(x_0) + \frac{\partial f(x_0)}{\partial x}\Delta x + \frac{\partial^2 f(x_0)}{\partial x^2}\frac{\Delta x^2}{2!} + \cdots $$
$$ f(x_0 - \Delta x) = f(x_0) - \frac{\partial f(x_0)}{\partial x}\Delta x + \frac{\partial^2 f(x_0)}{\partial x^2}\frac{\Delta x^2}{2!} + \cdots $$
$$ f(x_0 + \Delta x) + f(x_0 - \Delta x) = 2f(x_0) + \frac{2\partial^2f(x_0)}{\partial x^2}\frac{\Delta x^2}{2!} $$
$$ \frac{\partial^2f(x_0)}{\partial x^2} = \frac{f(x_0 + \Delta x) -2f(x_0) +f(x_0 - \Delta x)}{\Delta x^2} $$
$$ \frac{\partial^2f(y_0)}{\partial y^2} = \frac{f(y_0 + \Delta y) -2f(y_0) +f(y_0 - \Delta y)}{\Delta y^2} $$
$$ f_{xx}|_{ij} = \frac{f_{i+1j}-2f_{ij}+f_{i-1j}}{\Delta x^2} $$
$$ f_{yy}|_{ij} = \frac{f_{i+1j}-2f_{ij}+f_{i-1j}}{\Delta y^2} $$


### Discretización
Reemplazando $\widehat{f}_{xx}$ y $\widehat{f}_{yy}$ por la segunda derivada respectivamente de $x$ y de $y$, obtenemos: $$\frac{f_{i+1j}-2f_{ij}+f_{i-1j}}{\Delta x^2} + \frac{f_{ij+1}-2f_{ij}+f_{ij-1}}{\Delta y^2} = 0$$ que, al considerar $\beta = \frac{\Delta x}{\Delta y}$, se puede rescribir como: $$f_{i+1j}+\beta^2f_{ij+1}+f_{i-1j}+\beta^2f_{ij-1}-2(1+\beta^2)f_{ij} = 0$$ y al resolver para $f_{ij}$ obtenemos: $$f_{ij} = \frac{f_{i+1j}+\beta^2f_{ij+1}+f_{i-1j}+\beta^2f_{ij-1}}{2(1+\beta^2)}$$ que al observar la solución podemos apreciar que la solución para cada punto de la malla depende de los cuatro puntos vecinos a él dentro de la malla. En el caso cuando tengamos $\Delta x = \Delta y$, $\beta = 1$ por lo que tenemos las siguiente ecuaciones: $$f_{ij} = \frac{1}{4}(f_{i+1j}+f_{ij+1}+f_{i-1j}+f_{ij-1})$$ $$f_{i+1j}+f_{ij+1}+f_{i-1j}+f_{ij-1}-4f_{ij}=0$$

No existe una ventaja matemáticamente formal para usar $\beta = 1$, sin embargo, valores de $\beta$ más grandes que la unidad tienden a producir resultados menos certeros que cuando se utiliza un $\beta$ cerca de la vecindad de la unidad. 


In [171]:
import numpy as np

def add_boundaries(G, boundaries):
    """Adds the given boundaries to the matrix G
    
    Parameters
    ----------
    G : numpy.ndarray
        Matrix that will be used to model the thermal system, the center will allocate
        the temperature grid points interested in solving. While the first and last
        column and row will be allocate the thermal boundaries of the system. 
    boundaries : numpy.ndarray
        Must containt 4 numpy.ndarrays each representing one side of the thermal plate
        (top, right, bottom, left).

    Returns
    -------
    G
    """
    G[0] = boundaries[0]
    G[:,G.shape[1]-1] = boundaries[1]
    G[G.shape[0]-1] = boundaries[2]
    G[:,0] = boundaries[3]
    return G

def add_boundaries_test(d0=3, d1=3, i=1):
    """Generates random matrices to test"""
    G_raw = np.ones((d0,d1))
    B = np.random.rand(d0,d1)
    boundaries = np.array([B[0],B[:,d1-1],B[d0-1],B[:,0]])
    G_b = add_boundaries(G_raw.copy(), boundaries)
    print(f'Test #{i}: \nG:\n{G_raw}\nBoundaries:\n{boundaries}\nG\':\n{G_b}')

if __name__ == '__main__': 
    """Raw tests for add_boundaries(G, boundaries)"""
    add_boundaries_test(d0=7,d1=5)

Test #1: 
G:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Boundaries:
[array([0.55483516, 0.97590158, 0.71433358, 0.43997228, 0.71130734])
 array([0.71130734, 0.51368807, 0.26844317, 0.53597997, 0.64229286,
       0.09902127, 0.19102555])
 array([0.20305361, 0.96583063, 0.14673295, 0.99655726, 0.19102555])
 array([0.55483516, 0.13991227, 0.41050021, 0.26909499, 0.81463617,
       0.92934011, 0.20305361])]
G':
[[0.55483516 0.97590158 0.71433358 0.43997228 0.71130734]
 [0.13991227 1.         1.         1.         0.51368807]
 [0.41050021 1.         1.         1.         0.26844317]
 [0.26909499 1.         1.         1.         0.53597997]
 [0.81463617 1.         1.         1.         0.64229286]
 [0.92934011 1.         1.         1.         0.09902127]
 [0.20305361 0.96583063 0.14673295 0.99655726 0.19102555]]


In [122]:
def build_grid_matrix(h, w, deltaX, deltaY, boundaries):
    """Builds the grid matrix with boundaries and a given height h and width w

    Parameters
    ----------
    h : int
        Thermal system's height.
    w : int
        Thermal system's width.
    deltaX : float
        Grid's width of X axis.
    deltaY : float
        Grid's height of Y axis.
    boundaries : numpy.ndarray
        Must containt 4 numpy.ndarrays each representing one side of the thermal plate
        (top, right, bottom, left).

    Returns
    -------
    Matrix G
    """
    d0 = int(h//deltaY + 1)
    d1 = int(w//deltaX + 1)
    init_G = np.ones((d0, d1))
    G = add_boundaries(init_G, boundaries)
    return G

def build_grid_matrix_test(h, w, deltaX, deltaY, i=1):
    """Generates random tests for build_grid_matrix()"""
    d0 = int(h//deltaY + 1)
    d1 = int(w//deltaX + 1)
    B = np.random.rand(d0,d1)
    boundaries = np.array([B[0],B[:,d1-1],B[d0-1],B[:,0]])
    G = build_grid_matrix(h, w, deltaX, deltaY, boundaries)
    print(f'Test #{i}: \nG:\n{G}')

if __name__ == '__main__':
    """Tests for build_grid_matrix(h, w, deltaX, deltaY, boundaries)"""
    build_grid_matrix_test(15, 10, 2.5, 2.5, i=1)

Test #1: 
G:
[[0.91449239 0.68626234 0.53358516 0.00394333 0.64594516]
 [0.21282297 1.         1.         1.         0.47338987]
 [0.00825154 1.         1.         1.         0.60530188]
 [0.06434657 1.         1.         1.         0.89030797]
 [0.46262034 1.         1.         1.         0.36635174]
 [0.94809639 1.         1.         1.         0.05515341]
 [0.7415118  0.81961804 0.01016537 0.73331798 0.06244468]]


In [1]:
def get_d0_d1(h, w, deltaX, deltaY):
    """Returns the appropiate dimensions for the grid matrix G"""
    return int(h//deltaY + 1), int(w//deltaX + 1)

def build_A_B(G):
    """Builds the matrices A and B that satisfy the equation: AX=B where X
    is the temperature vector of the thermal system. 

    Parameters
    ----------
    G : numpy.ndarray
        Matrix  that already contains the boundaries to the thermal system.
    Returns
    -------
    A : numpy.ndarray
    B : numpy.ndarray
    """
    d0, d1 = G.shape[0], G.shape[1]
    dimA = (d0-2)*(d1-2)
    A = np.zeros((dimA, dimA))
    B = np.zeros((dimA, 1))
    n_row, n_T = 0, 0
    for row in range(1, d0-1):
        for col in range(1, d1-1):
            #Fill A matrix
            if (deltaX / deltaY) == 1:
                A[n_row][n_T] = -4
            else:
                A[n_row][n_T] = 2*(1+(deltaX/deltaY)**2)
            top_idx, right_idx, bottom_idx, left_idx = n_T-(d1-2), n_T+1, n_T+(d1-2), n_T-1
            if top_idx >= 0: A[n_T][top_idx] = 1
            if right_idx < (d1-2): A[n_T][right_idx] = 1
            if bottom_idx < (d0-2): A[n_T][bottom_idx] = 1
            if left_idx >= 0: A[n_T][left_idx] = 1
            top, right, bottom, left = G[row-1][col], G[row][col+1], G[row+1][col], G[row][col-1]
            #Check vertical position
            if row == 1: #T_i is adjacent to upper boundary
                B[n_T][0] -= top
            elif row == d0-2: #T_i is adjacent to lower boundary
                B[n_T][0] -= bottom
            #Check horizontal position
            if col == 1: #T_i is adjacent to left boundary
                B[n_T][0] -= left
            elif col == d1-2: #T_i is adjacent to right boundary
                B[n_T][0] -= right
            n_row += 1
            n_T += 1
    return A,B

In [273]:
def process_T(T, deltaX, deltaY, d0, d1):
    """Prints out nicely the matrix T containing the temperatures"""
    T_mod = []
    d1 -= 2
    d0 -= 2
    for i in range(d1):
        a = i
        for j in range(d0):
            T_mod.append(T[a][0])
            a += d1
    d0 += 2
    d1 += 2
    n_T = 0
    for col in range(1,d1-1):
        print(f'x={deltaX*col}[cm]:', end='')
        for row in range(d0-1,1,-1):
            if row == d0-1:
                print(f'\ty={deltaY*row-deltaY}[cm]  T(x,y)={np.round(T_mod[n_T],4)}')
            else:
                print(f'\t\ty={deltaY*row-deltaY}[cm]  T(x,y)={np.round(T_mod[n_T],4)}')
            n_T += 1
        print()

In [274]:
def find_temperatures(h, w, deltaX, deltaY, boundaries, verbose=False):
    G = build_grid_matrix(h, w, deltaX, deltaY, init_boundaries)
    A, B = build_A_B(G)
    T = np.linalg.solve(A, B)
    if verbose:
        print(f'Grid: \n {G}\n')
    process_T(T, deltaX, deltaY, d0, d1)

## Ejemplo del libro:
- $h=15$
- $w=10$
- $\Delta x = 2.5$
- $\Delta y = 2.5$

In [275]:
h, w = 15, 10
deltaX, deltaY = 2.5, 2.5
d0, d1 = get_d0_d1(h, w, deltaX, deltaY)
init_boundaries = np.array([
    [0,70.710678,100,70.710678,0], #top
    np.zeros(d0), #right
    np.zeros(d1), #bottom
    np.zeros(d0)  #left
])
find_temperatures(h, w, deltaX, deltaY, boundaries)

x=2.5[cm]:	y=12.5[cm]  T(x,y)=32.5016
		y=10.0[cm]  T(x,y)=15.2949
		y=7.5[cm]  T(x,y)=6.5426
		y=5.0[cm]  T(x,y)=2.6492
		y=2.5[cm]  T(x,y)=1.0406

x=5.0[cm]:	y=12.5[cm]  T(x,y)=44.0009
		y=10.0[cm]  T(x,y)=14.8239
		y=7.5[cm]  T(x,y)=5.3416
		y=5.0[cm]  T(x,y)=1.9977
		y=2.5[cm]  T(x,y)=0.7596

x=7.5[cm]:	y=12.5[cm]  T(x,y)=28.6779
		y=10.0[cm]  T(x,y)=10.8755
		y=7.5[cm]  T(x,y)=4.0543
		y=5.0[cm]  T(x,y)=1.513
		y=2.5[cm]  T(x,y)=0.5681



## Haciendo la malla más fina

In [276]:
h, w = 15, 10
deltaX, deltaY = 1, 1
d0, d1 = get_d0_d1(h, w, deltaX, deltaY)
init_boundaries = np.array([
    [0,0,70.710678,70.710678,100,100,100,70.710678,70.710678,0,0], #top
    np.zeros(d0), #right
    np.zeros(d1), #bottom
    np.zeros(d0)  #left
])
find_temperatures(h, w, deltaX, deltaY, boundaries)

x=1[cm]:	y=14[cm]  T(x,y)=9.2615
		y=13[cm]  T(x,y)=4.1076
		y=12[cm]  T(x,y)=2.1311
		y=11[cm]  T(x,y)=1.0465
		y=10[cm]  T(x,y)=0.4751
		y=9[cm]  T(x,y)=0.2022
		y=8[cm]  T(x,y)=0.0819
		y=7[cm]  T(x,y)=0.0319
		y=6[cm]  T(x,y)=0.0121
		y=5[cm]  T(x,y)=0.0045
		y=4[cm]  T(x,y)=0.0016
		y=3[cm]  T(x,y)=0.0006
		y=2[cm]  T(x,y)=0.0002
		y=1[cm]  T(x,y)=0.0001

x=2[cm]:	y=14[cm]  T(x,y)=32.9384
		y=13[cm]  T(x,y)=9.2615
		y=12[cm]  T(x,y)=2.8481
		y=11[cm]  T(x,y)=0.9737
		y=10[cm]  T(x,y)=0.3622
		y=9[cm]  T(x,y)=0.1411
		y=8[cm]  T(x,y)=0.0557
		y=7[cm]  T(x,y)=0.0219
		y=6[cm]  T(x,y)=0.0085
		y=5[cm]  T(x,y)=0.0032
		y=4[cm]  T(x,y)=0.0012
		y=3[cm]  T(x,y)=0.0004
		y=2[cm]  T(x,y)=0.0002
		y=1[cm]  T(x,y)=0.0001

x=3[cm]:	y=14[cm]  T(x,y)=42.5198
		y=13[cm]  T(x,y)=12.9453
		y=12[cm]  T(x,y)=3.9484
		y=11[cm]  T(x,y)=1.2305
		y=10[cm]  T(x,y)=0.3982
		y=9[cm]  T(x,y)=0.1348
		y=8[cm]  T(x,y)=0.0476
		y=7[cm]  T(x,y)=0.0174
		y=6[cm]  T(x,y)=0.0065
		y=5[cm]  T(x,y)=0.0024
		y=4[cm]

## $\Delta x \neq \Delta y$
- $\Delta x = 2$
- $\Delta y = 1$

In [279]:
h, w = 15, 10
deltaX, deltaY = 2, 1
d0, d1 = get_d0_d1(h, w, deltaX, deltaY)
init_boundaries = np.array([
    [0,70.710678,100,100,70.710678,0], #top
    np.zeros(d0), #right
    np.zeros(d1), #bottom
    np.zeros(d0)  #left
])
find_temperatures(h, w, deltaX, deltaY, boundaries)

x=2[cm]:	y=14[cm]  T(x,y)=35.5686
		y=13[cm]  T(x,y)=19.8478
		y=12[cm]  T(x,y)=9.6017
		y=11[cm]  T(x,y)=3.758
		y=10[cm]  T(x,y)=1.4334
		y=9[cm]  T(x,y)=0.5377
		y=8[cm]  T(x,y)=0.1996
		y=7[cm]  T(x,y)=0.0737
		y=6[cm]  T(x,y)=0.0271
		y=5[cm]  T(x,y)=0.01
		y=4[cm]  T(x,y)=0.0037
		y=3[cm]  T(x,y)=0.0013
		y=2[cm]  T(x,y)=0.0005
		y=1[cm]  T(x,y)=0.0002

x=4[cm]:	y=14[cm]  T(x,y)=51.7157
		y=13[cm]  T(x,y)=19.9218
		y=12[cm]  T(x,y)=8.1235
		y=11[cm]  T(x,y)=2.9704
		y=10[cm]  T(x,y)=1.1009
		y=9[cm]  T(x,y)=0.4096
		y=8[cm]  T(x,y)=0.1523
		y=7[cm]  T(x,y)=0.0565
		y=6[cm]  T(x,y)=0.0209
		y=5[cm]  T(x,y)=0.0077
		y=4[cm]  T(x,y)=0.0028
		y=3[cm]  T(x,y)=0.001
		y=2[cm]  T(x,y)=0.0004
		y=1[cm]  T(x,y)=0.0001

x=6[cm]:	y=14[cm]  T(x,y)=51.3725
		y=13[cm]  T(x,y)=19.5534
		y=12[cm]  T(x,y)=6.9192
		y=11[cm]  T(x,y)=2.4724
		y=10[cm]  T(x,y)=0.8933
		y=9[cm]  T(x,y)=0.3257
		y=8[cm]  T(x,y)=0.1195
		y=7[cm]  T(x,y)=0.044
		y=6[cm]  T(x,y)=0.0162
		y=5[cm]  T(x,y)=0.006
		y=4[cm]  T

## Cambiando condiciones de frontera

In [281]:
h, w = 15, 10
deltaX, deltaY = 2.5, 2.5
d0, d1 = get_d0_d1(h, w, deltaX, deltaY)
init_boundaries = np.array([
    [0,70.710678,100,70.710678,0], #top
    [0,50,75,100,75,50,0], #right
    np.zeros(d1), #bottom
    [0,50,75,100,75,50,0], #left
])
find_temperatures(h, w, deltaX, deltaY, boundaries)

x=2.5[cm]:	y=12.5[cm]  T(x,y)=55.0801
		y=10.0[cm]  T(x,y)=43.5671
		y=7.5[cm]  T(x,y)=44.8975
		y=5.0[cm]  T(x,y)=39.5664
		y=2.5[cm]  T(x,y)=30.368

x=5.0[cm]:	y=12.5[cm]  T(x,y)=56.0427
		y=10.0[cm]  T(x,y)=24.9025
		y=7.5[cm]  T(x,y)=17.45
		y=5.0[cm]  T(x,y)=14.2541
		y=2.5[cm]  T(x,y)=11.1555

x=7.5[cm]:	y=12.5[cm]  T(x,y)=44.1884
		y=10.0[cm]  T(x,y)=36.0227
		y=7.5[cm]  T(x,y)=38.3682
		y=5.0[cm]  T(x,y)=31.9056
		y=2.5[cm]  T(x,y)=23.2653



## $\Delta x = \Delta y = 1.25$

In [285]:
h, w = 15, 10
deltaX, deltaY = 1.25, 1.25
d0, d1 = get_d0_d1(h, w, deltaX, deltaY)
init_boundaries = np.array([
    [0,70.710678,70.710678,100,100,100,70.710678,70.710678,0], #top
    np.zeros(d0), #right
    np.zeros(d1), #bottom
    np.zeros(d0)  #left
])
find_temperatures(h, w, deltaX, deltaY, boundaries)

x=1.25[cm]:	y=13.75[cm]  T(x,y)=32.02
		y=12.5[cm]  T(x,y)=14.694
		y=11.25[cm]  T(x,y)=6.17
		y=10.0[cm]  T(x,y)=2.4598
		y=8.75[cm]  T(x,y)=0.9469
		y=7.5[cm]  T(x,y)=0.3552
		y=6.25[cm]  T(x,y)=0.1306
		y=5.0[cm]  T(x,y)=0.0473
		y=3.75[cm]  T(x,y)=0.0169
		y=2.5[cm]  T(x,y)=0.006
		y=1.25[cm]  T(x,y)=0.0021

x=2.5[cm]:	y=13.75[cm]  T(x,y)=42.6753
		y=12.5[cm]  T(x,y)=14.3423
		y=11.25[cm]  T(x,y)=5.1281
		y=10.0[cm]  T(x,y)=1.897
		y=8.75[cm]  T(x,y)=0.711
		y=7.5[cm]  T(x,y)=0.2666
		y=6.25[cm]  T(x,y)=0.0993
		y=5.0[cm]  T(x,y)=0.0366
		y=3.75[cm]  T(x,y)=0.0134
		y=2.5[cm]  T(x,y)=0.0048
		y=1.25[cm]  T(x,y)=0.0017

x=3.75[cm]:	y=13.75[cm]  T(x,y)=53.628
		y=12.5[cm]  T(x,y)=16.9926
		y=11.25[cm]  T(x,y)=5.5302
		y=10.0[cm]  T(x,y)=1.8568
		y=8.75[cm]  T(x,y)=0.6419
		y=7.5[cm]  T(x,y)=0.2271
		y=6.25[cm]  T(x,y)=0.0816
		y=5.0[cm]  T(x,y)=0.0296
		y=3.75[cm]  T(x,y)=0.0107
		y=2.5[cm]  T(x,y)=0.0039
		y=1.25[cm]  T(x,y)=0.0014

x=5.0[cm]:	y=13.75[cm]  T(x,y)=54.8442
		y=12.5[cm